"""backup.plan — PURE sync-planning core for BK-01 checkpoint auto-backup.

Decides WHICH completeness-checked checkpoints need uploading, honoring the D-BK-2 house default
(mirror EVERY complete checkpoint) and an idempotent skip (never re-upload an already-backed-up dir).
The Modal sync/restore functions that CONSUME this plan land in 09.1-08.

CRITICAL — pure-module discipline (mirrors modal/session_cap.py): this module imports NOTHING from
``modal``, ``torch``, ``peft``, ``huggingface_hub``, or ``train.checkpoint`` / ``lora.peft`` (both
pull torch). It is stdlib-only (``re``, ``pathlib``) and unit-testable on Windows with no GPU.

The completeness rule + checkpoint-naming constants below MIRROR ``train.checkpoint`` (the atomic
save's completeness contract, AUDIT-#3) and ``lora.peft.ADAPTER_FILENAME`` — they are re-declared
here (NOT imported, to keep the module torch-free). A drift-guard test
(``tests/test_backup_plan.py``) asserts these equal the canonical constants under ``importorskip``,
so the mirror can never silently drift.
"""

from __future__ import annotations

import re
from pathlib import Path

#: MIRRORS train.checkpoint.CHECKPOINT_PREFIX — the checkpoint dir name prefix.
CHECKPOINT_PREFIX = "checkpoint-step-"
#: MIRRORS train.checkpoint.TRAINING_STATE_FILENAME — the companion training-state file.
TRAINING_STATE_FILENAME = "training_state.pt"
#: MIRRORS lora.peft.ADAPTER_FILENAME — the PEFT adapter weights file. Named MIRRORED_* because
#: D-9-FILENAME (tests/test_adapter_filename_single_source.py) reserves the canonical name for its
#: single definition site; the drift-guard in tests/test_backup_plan.py pins this to the canonical.
MIRRORED_ADAPTER_FILENAME = "adapter_model.safetensors"

#: MIRRORS train.checkpoint._STEP_RE — parse the zero-padded step out of a checkpoint dir name.
_STEP_RE = re.compile(rf"^{re.escape(CHECKPOINT_PREFIX)}(\d+)")

#: The files that must ALL be present in a DESTINATION checkpoint dir for it to count as a COMPLETE
#: backup (WR-01) — the SAME completeness contract ``is_complete`` applies to the SOURCE, now applied
#: to the mirrored copy so a half-uploaded dir is never trusted on its bare name.
REQUIRED_BACKUP_FILES: frozenset[str] = frozenset(
    {MIRRORED_ADAPTER_FILENAME, TRAINING_STATE_FILENAME}
)

#: Basenames the mirror deliberately does NOT carry (D-10-DEF-18). The mirror is otherwise a 1:1
#: copy of each complete checkpoint dir; this is the ONE documented subtraction, and it is stated
#: here rather than inlined at the upload call sites so it is greppable, unit-testable, and applied
#: IDENTICALLY to every destination (a ``restore`` from ``local`` must yield the same tree as a
#: ``restore`` from ``hf`` — the backup contract is destination-INDEPENDENT).
#:
#: WHY ``README.md``: PEFT's ``save_pretrained`` auto-generates a model card whose YAML front matter
#: carries ``base_model: <the base model's config._name_or_path>``. Under ``family: h3`` that is a
#: LOCAL VOLUME PATH (``/weights/minimax-h3/transformer_ref``), and ``huggingface_hub`` validates
#: README front matter server-side BEFORE hashing a single byte
#: (``hf_api._prepare_upload_folder_additions`` -> ``_validate_yaml`` -> ``POST /api/validate-yaml``),
#: which answers HTTP 400 ``"base_model" ... is not valid. Use a model id from https://hf.co/models``.
#: Because that fires on the FIRST dir, the ENTIRE mirror aborts and ZERO checkpoints upload.
#:
#: WHY OMITTING IT IS SAFE, AND WHAT IT COSTS (measured, not assumed):
#:   * NOT completeness-critical — ``REQUIRED_BACKUP_FILES`` is adapter + ``training_state.pt`` only,
#:     and ``tests/test_backup_plan.py`` PINS the two sets disjoint so this can never regress into
#:     excluding a file that ``complete_remote_names`` then waits for forever.
#:   * NOT load-bearing — nothing in ``src/signet_trainer`` reads a checkpoint README.
#:   * The LTX-family README carries NO ``base_model`` key at all: it is 100% boilerplate, so that
#:     path loses literally nothing. The H3 README's ``base_model`` line is the only in-dir record of
#:     base-model provenance (``adapter_config.json`` has ``base_model_name_or_path: null``); that
#:     breadcrumb survives on the Volume copy, in the git-tracked config that names the model, and is
#:     regenerated by the next ``save_pretrained``.
#: The rejected alternative was uploading a REWRITTEN README: it cannot be done in one
#: ``upload_folder`` (staging a corrected file means copying the multi-GB dir to temp), it would put a
#: file PEFT never wrote into the durable mirror, and any "valid" rewrite either drops the same key
#: anyway or ASSERTS an unverified Hub id. Durability code should be boring.
MIRROR_EXCLUDED_FILES: frozenset[str] = frozenset({"README.md"})


def is_complete(path: Path) -> bool:
    """True iff BOTH the adapter and ``training_state.pt`` exist under ``path``.

    MIRRORS ``train.checkpoint.CheckpointManager._is_complete`` — a half-written checkpoint dir
    (one file missing) is never selected for backup (threat T-09.1-07-D, AUDIT-#3 completeness rule).
    """
    return (path / MIRRORED_ADAPTER_FILENAME).exists() and (path / TRAINING_STATE_FILENAME).exists()


def _step_of(path: Path) -> int:
    """The parsed integer step of a ``checkpoint-step-*`` dir (``-1`` if it does not match)."""
    match = _STEP_RE.match(path.name)
    return int(match.group(1)) if match else -1


def list_complete_checkpoints(local_dir: Path) -> list[Path]:
    """The COMPLETE ``checkpoint-step-*`` dirs under ``local_dir``, sorted by step ascending.

    Only regex-matching dirs that pass ``is_complete`` are returned — a half-written dir is excluded
    (mirrors ``_all_checkpoints`` + the completeness filter). Returns ``[]`` if ``local_dir`` is
    absent (cold start).
    """
    if not local_dir.exists():
        return []
    dirs = [
        d
        for d in local_dir.iterdir()
        if d.is_dir() and _STEP_RE.match(d.name) is not None and is_complete(d)
    ]
    return sorted(dirs, key=_step_of)


def select_for_backup(
    complete: list[Path], what: str, interval: int | None
) -> list[Path]:
    """The D-BK-2 scope selector over an already-completeness-filtered, step-sorted list.

    * ``what='all'`` (the HOUSE DEFAULT) -> EVERY complete dir (intermediates ARE the artifacts).
    * ``what='final'`` -> only the max-step dir (a narrowing for other users; never the default).
    * ``what='final+intervals'`` -> the max-step dir PLUS every dir whose step % interval == 0.

    Never returns final-only unless ``what`` is explicitly ``'final'``. The returned list stays
    sorted by step ascending. Raises on an unknown ``what`` (fail-fast; the config Literal already
    constrains it, this is belt-and-braces).
    """
    if not complete:
        return []
    if what == "all":
        return list(complete)
    final = complete[-1]  # max step (list is step-ascending)
    if what == "final":
        return [final]
    if what == "final+intervals":
        if interval is None or interval <= 0:
            raise ValueError(
                "select_for_backup(what='final+intervals') requires a positive interval "
                f"(got {interval!r})."
            )
        selected = [d for d in complete if _step_of(d) % interval == 0]
        if final not in selected:
            selected.append(final)
        return sorted(selected, key=_step_of)
    raise ValueError(
        f"unknown backup scope what={what!r}: expected one of 'all', 'final', 'final+intervals'."
    )


def complete_remote_names(remote_dir_files: dict[str, set[str]]) -> set[str]:
    """Dir names whose DESTINATION file set proves a COMPLETE backup (WR-01).

    ``remote_dir_files`` maps each backed-up dir name -> the set of file basenames present under it
    at the destination. A dir counts as backed-up ONLY when its files are a SUPERSET of
    ``REQUIRED_BACKUP_FILES`` (adapter + ``training_state.pt``). A partially-uploaded dir (its name
    present but a required file missing after an interrupted upload/copy) is NOT returned, so
    ``plan_uploads`` re-selects it for repair rather than trusting the bare name — completeness is now
    checked on the DESTINATION, not only the source.
    """
    return {
        name
        for name, files in remote_dir_files.items()
        if REQUIRED_BACKUP_FILES <= files
    }


def plan_uploads(selected: list[Path], remote_names: set[str]) -> list[Path]:
    """The idempotent upload plan: ``selected`` dirs NOT already backed up COMPLETELY.

    The backup layout mirrors the Volume 1:1 (dirs keep their real ``checkpoint-step-*`` names). To
    stay idempotent AND self-repairing (WR-01), ``remote_names`` must be the set of dirs whose
    DESTINATION copy is COMPLETE — the caller derives it from ``complete_remote_names`` (HF) or a
    per-dir ``is_complete`` re-check (local), NEVER from a bare directory listing. A dir present in
    ``remote_names`` (i.e. fully mirrored) is skipped; a name that is absent — whether never uploaded
    OR uploaded incompletely — is re-selected. Running twice with the first pass's COMPLETE names in
    ``remote_names`` returns ``[]`` (idempotent; 09.1-08's restore is a straight copy-back, D-BK-4).
    """
    return [d for d in selected if d.name not in remote_names]
