"""Typed-state emitter (TS-01a + TS-01b) — prose artifacts embed GENERATED state, never hand-copies.

"Typed State Beats Prose" (KNOWLEDGE `typed-state`, operator-adopted 2026-07-14): under cascaded
compaction, prose summaries corrupted 36.4% of numeric probes vs 9.4% for typed ``name: value``
blocks. The in-house failure this kills: the $250-vs-$260 ledger drift, where hand-copied
prose figures staled while the typed SESSION-STATE.json stayed right. Rule: never paraphrase a
computed value where a ``name: value`` line carries it verbatim.

This module renders the ``TYPED-STATE`` blocks embedded in prose artifacts (training card,
``.continue-here.md``, ``STATE.md`` Session Continuity) FROM the typed sources of truth:

Two classes of source, addressed two different ways (the packaging split): SPEC/TEMPLATE files ship
as PACKAGE DATA (``signet_trainer.harness_data``, resolved via ``importlib.resources`` so they work
from an installed wheel with no ``.planning/`` on disk); LIVE per-project state stays under
``.planning/harness/`` and is resolved against ``project_root()``, which fails with an actionable
message rather than a stack trace when there is no project.

  * ``.planning/harness/cards/<card>.state.yaml`` (LIVE) — the typed campaign core (TS-01b):
    campaign identity, per-round records, and the live ``current`` slots. Edit THAT file, never
    the emitted blocks.
  * ``.planning/harness/SESSION-STATE.json`` (LIVE) — the SINGLE numeric source of truth for spend/cap.
    The spent figure is read via ``signet_trainer.modal.session_cap.read_ledger`` (the one
    authoritative ledger reader — never re-summed ad hoc); ``session_cap_usd`` and the entry
    count are read from the same JSON directly because ``session_cap`` exposes no getter for them.
  * ``HOUSE-SPEC.yaml`` (PACKAGED — ``signet_trainer.harness_data``) — the typed home of the house VERDICT spec (D-29): the
    locked eval params (``frame_count`` / ``num_inference_steps`` / ``guidance_scale`` / ``seed`` /
    ``two_stage_upscale`` / ``min_prompt_count``) that ``assert_verdict_spec`` asserts a verdict
    render against. These are DELIBERATELY different from ``schema.py::ValidationConfig`` defaults
    (the LTX-canonical params) — schema.py stays zero-edit; the divergence is intentional (Plan 01
    F-3). ``load_house_spec`` reads it, fail-LOUD.
  * ``TIER-TAXONOMY.yaml`` (PACKAGED — ``signet_trainer.harness_data``) — the knob->tier partition (D-30 part 1). The
    KNOWLEDGE.md knob->tier table is EMITTED from it via ``render_tier_table`` (D-30 part 2 — the
    drift fence: a hand-written table beside the YAML would silently diverge). ``load_tier_taxonomy``
    reads it, fail-LOUD.

Ownership boundary inside prose artifacts — the marker convention::

    <!-- TYPED-STATE:BEGIN (generated by signet_trainer.harness_state — edit the SOURCES, not this block) -->
    ...emitted yaml code-fence...
    <!-- TYPED-STATE:END -->

``emit_into`` REPLACES only the content between the markers (creating the marker section right
after a named anchor heading when absent), is idempotent (same block twice -> byte-identical
file), and FAILS LOUD on malformed/nested/unbalanced markers rather than guessing. Everything
outside the markers (findings, corrections, verdicts, narrative) is human prose and is never
touched.

Import-confined (Anti-Pattern 6): yaml/json/stdlib + ``signet_trainer.modal.session_cap`` (itself
pure stdlib — verified: importing it pulls neither ``modal`` nor ``torch``). NO torch, NO modal,
NO network — runs free on Windows/CI.

Config seams:
  * The active campaign card is DISCOVERED, never hardcoded: ``discover_campaign_state_path``
    globs ``cards/TRAINING-CARD-*.state.yaml`` under the repo root (exactly one card == the
    active campaign). With MULTIPLE cards, set the ``SIGNET_CAMPAIGN`` env var to the campaign
    slug (the ``<slug>`` in ``TRAINING-CARD-<slug>.state.yaml``) to pin the active one — an
    ambiguous or empty cards dir fails LOUD. ``artifact_registry`` derives the card's companion
    ``.md`` artifact from the discovered state path; the non-campaign artifacts stay in
    ``STATIC_ARTIFACTS``.
  * NO live-Volume source mode is implemented. TS-01a names Volume listings as a potential
    source; that mode is deliberately absent in v1 (it would need a network call — off by
    default and untested-against-network per the house test rules). The typed sources above are
    all local files.

CLI (module runs as ``python -m signet_trainer.harness_state`` from the repo root)::

    PYTHONPATH=src PYTHONUTF8=1 python -m signet_trainer.harness_state emit [--dry-run]

``--dry-run`` prints the rendered block + per-artifact action (replace/create/unchanged) and
writes NOTHING.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

from signet_trainer import harness_data
from signet_trainer.modal.session_cap import read_ledger

# --------------------------------------------------------------------------- marker convention

# The FULL canonical marker lines (what emit_into writes). Detection is by the stable prefixes
# below so a hand-edited parenthetical can't silently orphan a section — but the canonical lines
# are always what gets (re)written.
MARKER_BEGIN = (
    "<!-- TYPED-STATE:BEGIN "
    "(generated by signet_trainer.harness_state — edit the SOURCES, not this block) -->"
)
MARKER_END = "<!-- TYPED-STATE:END -->"

_MARKER_BEGIN_PREFIX = "<!-- TYPED-STATE:BEGIN"
_MARKER_END_PREFIX = "<!-- TYPED-STATE:END"

# MASK-SPEC block markers — DISTINCT from the TYPED-STATE markers above. KNOWLEDGE.md now holds BOTH
# the tier-table TYPED-STATE block AND the mask-spec block; ``_splice`` counts markers by their
# stable PREFIX, so a second TYPED-STATE pair in one file would trip the "duplicated/nested" fence.
# A block-type-specific marker set lets each file carry one of EACH block type without collision.
MASK_SPEC_MARKER_BEGIN = (
    "<!-- MASK-SPEC:BEGIN "
    "(generated by signet_trainer.harness_state — edit MASK-SPEC.yaml, not this block) -->"
)
MASK_SPEC_MARKER_END = "<!-- MASK-SPEC:END -->"

_MASK_SPEC_BEGIN_PREFIX = "<!-- MASK-SPEC:BEGIN"
_MASK_SPEC_END_PREFIX = "<!-- MASK-SPEC:END"

# --------------------------------------------------------------------------- registry (v1 seam)

# --- two kinds of source, two kinds of default -------------------------------------------------
#
# SPEC/TEMPLATE data (HOUSE-SPEC / TIER-TAXONOMY / MASK-SPEC) is the same for every install and now
# ships as PACKAGE DATA under ``signet_trainer.harness_data``, resolved through
# ``importlib.resources``. It used to be addressed as ``REPO_ROOT / ".planning/harness/<f>"``, which
# only resolved inside the maintainer's checkout — a fresh `pip install` got a dangling default.
#
# LIVE STATE (SESSION-STATE.json, the campaign cards, KNOWLEDGE.md, the emitted prose artifacts) is
# per-project, operator-written, and must NOT ship. It stays PROJECT-RELATIVE and is resolved
# against ``project_root()`` below, which fails with an actionable message rather than a stack
# trace when there is no project to read.

# Where the LIVE per-project harness state lives, relative to the project root.
PLANNING_HARNESS_DIR = ".planning/harness"
PROJECT_ROOT_ENV_VAR = "SIGNET_PROJECT_ROOT"  # explicit override for the live-state project root

# The checkout this module was imported from (src/signet_trainer/harness_state.py -> parents[2]).
# Correct in the source repo; meaningless from site-packages — hence project_root() below.
REPO_ROOT = Path(__file__).resolve().parents[2]

# Typed LIVE sources. The campaign card is NOT a constant: it is discovered per-project (see
# discover_campaign_state_path below).
CARDS_DIR = f"{PLANNING_HARNESS_DIR}/cards"
CARD_STATE_PREFIX = "TRAINING-CARD-"
CARD_STATE_SUFFIX = ".state.yaml"
CAMPAIGN_ENV_VAR = "SIGNET_CAMPAIGN"  # pins the campaign slug when multiple cards exist
SESSION_STATE_PATH = f"{PLANNING_HARNESS_DIR}/SESSION-STATE.json"

# Typed PACKAGED sources — real filesystem paths inside the installed package (or the
# SIGNET_HARNESS_DATA_DIR override). Resolved lazily so an incomplete install fails at the call that
# needs the spec, with that spec named, rather than at import time.


def house_spec_path() -> Path:
    """Path of the packaged house VERDICT spec (``HOUSE-SPEC.yaml``)."""
    return harness_data.spec_path(harness_data.HOUSE_SPEC)


def tier_taxonomy_path() -> Path:
    """Path of the packaged knob->tier partition (``TIER-TAXONOMY.yaml``)."""
    return harness_data.spec_path(harness_data.TIER_TAXONOMY)


def mask_spec_path() -> Path:
    """Path of the packaged inpaint mask conventions (``MASK-SPEC.yaml``)."""
    return harness_data.spec_path(harness_data.MASK_SPEC)


def project_root(explicit: Path | None = None) -> Path:
    """The project root that owns the LIVE harness state (the dir holding ``.planning/harness``).

    Resolution order, first hit wins:

      1. ``explicit`` — what a caller passed (tests, ``emit_all(repo_root=...)``).
      2. ``SIGNET_PROJECT_ROOT`` — the explicit env override.
      3. the nearest ancestor of the CWD that carries ``.planning/harness`` (the normal case: the
         harness CLI is run from somewhere inside the project).
      4. ``REPO_ROOT`` — the checkout this module lives in (correct only for a source checkout).

    Never raises: a root is always returned so the CALLER can name the specific missing artifact.
    """
    if explicit is not None:
        return Path(explicit)
    env = os.environ.get(PROJECT_ROOT_ENV_VAR, "").strip()
    if env:
        return Path(env)
    cwd = Path.cwd().resolve()
    for candidate in (cwd, *cwd.parents):
        if (candidate / PLANNING_HARNESS_DIR).is_dir():
            return candidate
    return REPO_ROOT


def _missing_live_state(lead: str, root: Path) -> str:
    """The one actionable message for absent LIVE state — never a bare stack trace.

    ``lead`` is the caller's own first line (kept verbatim so existing error contracts hold); this
    appends WHERE the project root came from and HOW to point it somewhere else.
    """
    return (
        f"{lead}\n"
        f"    resolved against project root {root} (live harness state is PROJECT-relative and is "
        f"deliberately NOT shipped with the package).\n"
        f"    fix: run this from inside a signet-trainer project (a directory carrying "
        f"{PLANNING_HARNESS_DIR}/), or set {PROJECT_ROOT_ENV_VAR}=/path/to/project."
    )


def discover_campaign_state_path(repo_root: Path | None = None) -> str:
    """Repo-relative posix path of the ACTIVE campaign's ``.state.yaml`` card. Fails LOUD.

    Discovery, not configuration-by-code: glob ``cards/TRAINING-CARD-*.state.yaml`` under
    ``repo_root``. Exactly one card == the active campaign. With multiple cards the
    ``SIGNET_CAMPAIGN`` env var must name the active slug (``TRAINING-CARD-<slug>.state.yaml``);
    zero cards (or a pinned slug with no card) raises ``FileNotFoundError``; an unpinned
    multi-card dir raises ``ValueError`` listing the candidates. No campaign name is ever
    hardcoded here.
    """
    root = project_root(repo_root)
    cards_dir = root / CARDS_DIR
    pattern = f"{CARD_STATE_PREFIX}*{CARD_STATE_SUFFIX}"
    candidates = sorted(cards_dir.glob(pattern))
    slug = os.environ.get(CAMPAIGN_ENV_VAR)
    if slug:
        pinned = cards_dir / f"{CARD_STATE_PREFIX}{slug}{CARD_STATE_SUFFIX}"
        if not pinned.is_file():
            raise FileNotFoundError(
                f"{CAMPAIGN_ENV_VAR}={slug!r} names no campaign card: {pinned} not found "
                f"(available: {[c.name for c in candidates]})"
            )
        return (Path(CARDS_DIR) / pinned.name).as_posix()
    if not candidates:
        raise FileNotFoundError(
            _missing_live_state(
                f"no campaign card found: {cards_dir}/{pattern} matched nothing — create the "
                f"campaign's typed card (TS-01b) before emitting",
                root,
            )
        )
    if len(candidates) > 1:
        raise ValueError(
            f"multiple campaign cards found in {cards_dir}: {[c.name for c in candidates]} — "
            f"set {CAMPAIGN_ENV_VAR}=<slug> to pin the active campaign (never guessed)"
        )
    return (Path(CARDS_DIR) / candidates[0].name).as_posix()


def campaign_card_md_path(state_rel_path: str) -> str:
    """The campaign card's companion prose ``.md`` artifact for a ``.state.yaml`` relpath."""
    if not state_rel_path.endswith(CARD_STATE_SUFFIX):
        raise ValueError(f"not a campaign state path (missing {CARD_STATE_SUFFIX!r}): {state_rel_path}")
    return state_rel_path[: -len(CARD_STATE_SUFFIX)] + ".md"


# (artifact, anchor-heading) pairs — the anchor is only used to CREATE the marker section when a
# registered artifact has none yet; anchor match is prefix-based because headings carry trailing
# annotations (e.g. "## TYPED STATE (quotable slots — ...)"). The campaign card's .md is NOT
# listed here — it is discovered (artifact_registry) alongside its .state.yaml source.
STATIC_ARTIFACTS: list[tuple[str, str]] = [
    (
        ".planning/phases/09-address-tech-debt-offloader-seam-lora-utility-dedup/"
        ".continue-here.md",
        "## TYPED STATE",
    ),
    (".planning/STATE.md", "## Session Continuity"),
]


def artifact_registry(repo_root: Path | None = None) -> list[tuple[str, str]]:
    """The full (artifact, anchor) registry: the DISCOVERED campaign card .md + the static set."""
    state_rel = discover_campaign_state_path(repo_root)
    return [(campaign_card_md_path(state_rel), "## TYPED STATE"), *STATIC_ARTIFACTS]

# The knob->tier table (D-30 part 2) is emitted into KNOWLEDGE.md — a SEPARATE artifact/anchor from
# artifact_registry (which carries the campaign/ledger block). One block type per file: KNOWLEDGE.md
# receives ONLY the tier table, the three registry artifacts receive ONLY the campaign block.
# ``emit_into`` is block-agnostic, so this second emission needs no _splice change. Anchor match is
# prefix-based (the real heading carries a trailing annotation after this prefix).
TAXONOMY_ARTIFACT: tuple[str, str] = (
    ".planning/harness/KNOWLEDGE.md",
    "### `tier` `draft` `pro` `optimization_target` `carve-out`",
)

# The mask-spec block (Plan 09.3-01) is emitted into KNOWLEDGE.md too, at its OWN anchor + its OWN
# marker type (MASK_SPEC_MARKER_*). KNOWLEDGE.md thus carries TWO distinct emitted sections — the
# tier table (TYPED-STATE markers) and the mask conventions (MASK-SPEC markers) — one block type per
# marker set, so ``_splice`` never sees them as duplicated. ``check_stale`` covers this emission for
# FREE via its ``emit_all(dry_run=True)`` delegation.
MASK_SPEC_ARTIFACT: tuple[str, str] = (
    ".planning/harness/KNOWLEDGE.md",
    "### `mask-spec` `hex` `chroma` `polarity` `coverage` `dims`",
)


# --------------------------------------------------------------------------- typed sources


def load_campaign_state(path: str | Path) -> dict:
    """Load + shape-check the typed campaign core (``<card>.state.yaml``). Fails LOUD.

    Requires the three top-level keys (``campaign`` with ``slug``/``phase``, ``rounds`` list,
    ``current`` mapping) — a half-written source must never render a plausible-looking block.
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"campaign state file not found: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"campaign state {path}: top level must be a mapping, got {type(data).__name__}")
    campaign = data.get("campaign")
    if not isinstance(campaign, dict) or not campaign.get("slug") or not campaign.get("phase"):
        raise ValueError(f"campaign state {path}: 'campaign' must be a mapping with 'slug' and 'phase'")
    if not isinstance(data.get("rounds"), list) or not data["rounds"]:
        raise ValueError(f"campaign state {path}: 'rounds' must be a non-empty list of round records")
    if not isinstance(data.get("current"), dict):
        raise ValueError(f"campaign state {path}: 'current' must be a mapping of live slots")
    return data


def read_ledger_figures(session_state_path: str | Path) -> dict:
    """The ledger slice of the emitted block, from SESSION-STATE.json (single numeric source).

    ``spent_est_usd`` comes from ``session_cap.read_ledger`` — the ONE authoritative spend
    reader (its fail-closed semantics for corrupt ledgers carry over verbatim: a corrupt file
    raises rather than rendering a stale/wrong figure). ``session_cap_usd`` + the entry count
    are read from the same JSON directly (``session_cap`` has no getter for them — noted seam).
    A missing file is a fresh session: spent 0.0, cap ``null``, 0 entries.
    """
    path = Path(session_state_path)
    spent = read_ledger(path)  # canonical read — raises LOUDLY on a corrupt ledger
    cap = None
    entries = 0
    if path.is_file():
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            cap = data.get("session_cap_usd")
            spend = data.get("spend", [])
            entries = len(spend) if isinstance(spend, list) else 0
    return {
        # round(2) only trims float-sum noise (276.79999... -> 276.8); it never paraphrases.
        "spent_est_usd": round(spent, 2),
        "session_cap_usd": cap,
        "entries": entries,
        "source": Path(session_state_path).as_posix(),
    }


# --------------------------------------------------------------------------- house verdict spec


def load_house_spec(path: str | Path) -> dict:
    """Load + shape-check the house VERDICT spec (``HOUSE-SPEC.yaml``). Fails LOUD.

    The house verdict spec is house law: its absence is never "no constraint" (raises
    ``FileNotFoundError``), and a malformed spec raises ``ValueError`` naming the file (mirroring
    ``load_campaign_state``). Requires ``verdict_spec`` to carry ``frame_count`` /
    ``num_inference_steps`` / ``guidance_scale`` / ``seed`` / ``min_prompt_count``. These params are
    DELIBERATELY different from ``schema.py::ValidationConfig`` defaults (Plan 01 F-3) — do not
    reconcile them; ``schema.py`` is zero-edit.
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"house spec file not found: {path} (the verdict spec is house law)")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"house spec {path}: top level must be a mapping, got {type(data).__name__}")
    spec = data.get("verdict_spec")
    required = ("frame_count", "num_inference_steps", "guidance_scale", "seed", "min_prompt_count")
    if not isinstance(spec, dict):
        raise ValueError(f"house spec {path}: 'verdict_spec' must be a mapping")
    missing = [k for k in required if k not in spec]
    if missing:
        raise ValueError(
            f"house spec {path}: 'verdict_spec' is missing required keys {missing}; "
            f"a half-written verdict spec must never gate a metered render"
        )
    return data


# The locked verdict params compared param-for-param (D-24/D-25). ``min_prompt_count`` is handled
# separately (a length check, not an equality check).
_VERDICT_COMPARE_KEYS = (
    "frame_count",
    "num_inference_steps",
    "guidance_scale",
    "seed",
    "two_stage_upscale",
)

# WR-01: keys whose OMISSION from a render config's ``validation:`` block is legitimately equivalent
# to a value (because ``schema.py::ValidationConfig`` supplies that default when the field is absent).
# ``two_stage_upscale`` defaults to ``False`` in schema.py AND the house verdict value IS ``False`` —
# so a config that simply omits the key still runs single-stage and is compliant, not a violation.
# We materialize that one schema default HERE (rather than resolving the whole config through
# Pydantic) so ``schema.py`` stays zero-edit; an EXPLICIT ``true`` is still a real mismatch and fails
# loud. Keys NOT in this map keep the old ``None``-on-absence behavior (a verdict config must declare
# ``frame_count`` / ``seed`` / etc. explicitly — an omitted lock is still a mismatch).
_VERDICT_KEY_SCHEMA_DEFAULTS = {
    "two_stage_upscale": False,
}


def assert_verdict_spec(validation: dict, render_tier: str, house_spec: dict) -> None:
    """Assert a render config's ``validation`` block matches the house verdict spec (D-24/D-25/D-29).

    ``validation`` is a plain mapping of the render config's ``validation:`` block (a dict — NOT a
    Pydantic model; this module never imports ``schema.py``). ``render_tier`` is the CALL-SITE
    declaration (D-24): a render is a ``verdict`` BECAUSE a go/no-go decision rides on it.

      * ``quicklook`` -> returns immediately (mode-cheapenable, D-24).
      * ``verdict``   -> compares the locked params + the prompt-count floor; raises ``ValueError``
                         listing EVERY mismatch (a trimmed render usually trims several).
      * unknown tier  -> raises ``ValueError`` listing the valid tiers (never silently passes).

    This function NEVER reads the posture / mode and takes NO posture parameter: the verdict tier is
    locked and is NOT a mode lever (D-24). Plan 07 AST-scans this function to prove the posture never
    leaks into the verdict path — so its source deliberately names none of the posture tokens.
    """
    spec = house_spec["verdict_spec"]
    valid_tiers = house_spec.get("render_tiers") or ["quicklook", "verdict"]
    if render_tier not in valid_tiers:
        raise ValueError(
            f"unknown render_tier {render_tier!r}; valid tiers are {list(valid_tiers)} — "
            "an unrecognized tier is never waved through (it defaults to the strict verdict check "
            "at the CLI, and here it fails loud)"
        )
    if render_tier == "quicklook":
        return  # quicklook is a dev-glance render, free for the mode to cheapen (D-24).

    # render_tier == "verdict": the locked check. Collect ALL mismatches, then raise once.
    mismatches: list[str] = []
    for key in _VERDICT_COMPARE_KEYS:
        if key not in spec:
            continue
        expected = spec[key]
        # WR-01: fall back to the schema default for keys whose absence is legitimately equivalent
        # to that default (``two_stage_upscale`` -> False). For every other key the fallback is None,
        # preserving the old "an omitted lock is a mismatch" behavior.
        actual = validation.get(key, _VERDICT_KEY_SCHEMA_DEFAULTS.get(key))
        if actual != expected:
            mismatches.append(f"{key}: got {actual!r}, house verdict spec requires {expected!r}")

    min_prompts = spec.get("min_prompt_count", 1)
    prompts = validation.get("prompts", [])
    n_prompts = len(prompts) if isinstance(prompts, (list, tuple)) else 0
    if n_prompts < min_prompts:
        mismatches.append(
            f"prompt count: got {n_prompts}, house verdict spec requires >= {min_prompts} "
            "(D-25: a verdict render may not trim the prompt count — one prompt is never a valid "
            "verdict basis)"
        )

    if mismatches:
        raise ValueError(
            "verdict render REJECTED — trimmed params do not match the house verdict spec. "
            "This is the D-25 fence: a trimmed verdict render is the most expensive possible false "
            "economy, because a real go/no-go call (continue vs restart the recipe) rides on it, and "
            "that decision costs ROUNDS. Mismatches:\n  " + "\n  ".join(mismatches)
        )


# --------------------------------------------------------------------------- tier taxonomy table


def load_tier_taxonomy(path: str | Path) -> dict:
    """Load + shape-check the knob->tier taxonomy (``TIER-TAXONOMY.yaml``). Fails LOUD.

    Raises ``FileNotFoundError`` on absence and ``ValueError`` naming the path if ``knobs`` is
    absent/empty or ``default_tier != 3``. D-06 is load-bearing: a taxonomy that fails safe to Tier 1
    is a safety hole, not a typo — an absent knob must default to Tier 3 (ask), never Tier 1 (auto).
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"tier taxonomy file not found: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"tier taxonomy {path}: top level must be a mapping, got {type(data).__name__}")
    knobs = data.get("knobs")
    if not isinstance(knobs, dict) or not knobs:
        raise ValueError(f"tier taxonomy {path}: 'knobs' must be a non-empty mapping of knob->tier")
    # WR-02: every knob VALUE must be the one-line flow-mapping shape the dual-parser contract
    # requires — a mapping carrying an int ``tier`` in {1, 2, 3}. Without this, a malformed scalar
    # entry (``foo: bar``) passes the non-empty check above and then crashes ``render_tier_table``
    # with an opaque ``AttributeError: 'str' object has no attribute 'get'`` instead of the intended
    # fail-loud ValueError. Validate the shape at the LOADER so the failure names the offending knob
    # and the file, not a stack trace inside the renderer. (``bool`` is an ``int`` subclass in Python,
    # and ``True == 1`` — exclude it explicitly so ``tier: true`` is rejected, not silently Tier 1.)
    for name, meta in knobs.items():
        tier = meta.get("tier") if isinstance(meta, dict) else None
        if not isinstance(meta, dict) or isinstance(tier, bool) or not isinstance(tier, int) or tier not in (1, 2, 3):
            raise ValueError(
                f"tier taxonomy {path}: knob {name!r} must be a mapping with an int 'tier' in "
                f"{{1, 2, 3}} (the one-line flow-mapping shape the dual-parser contract requires); "
                f"got {meta!r}"
            )
    if data.get("default_tier") != 3:
        raise ValueError(
            f"tier taxonomy {path}: 'default_tier' must be 3 (D-06 fail-safe — an absent knob is "
            f"Tier 3/ask, never Tier 1/auto); got {data.get('default_tier')!r}"
        )
    return data


def render_tier_table(taxonomy: dict) -> str:
    """Render the knob->tier partition as a deterministic markdown block (D-30 part 2).

    Returns a markdown table (one row per knob under ``knobs``, sorted by tier then knob name),
    marks any ``fenced: true`` knob visibly as hard-fenced (D-07), and renders the
    ``not_a_mode_lever`` entries in a SEPARATE labelled list so no tier is inferable for them.
    Deterministic (mirrors ``render_state_block``): re-rendering unchanged input is byte-identical.
    Every knob row carries its ``source_tags`` — which satisfies
    ``test_knowledge_recommendation_sections_are_source_tagged``. NO ``#``-prefixed lines (they would
    be mis-parsed as markdown headings by the KNOWLEDGE.md section scanners).
    """
    knobs = taxonomy["knobs"]
    tiers = taxonomy.get("tiers", {})
    rows = sorted(knobs.items(), key=lambda kv: (kv[1].get("tier", 3), str(kv[0])))

    lines: list[str] = []
    lines.append(
        "_Generated from src/signet_trainer/harness_data/TIER-TAXONOMY.yaml — edit that file, then regenerate: "
        "PYTHONPATH=src PYTHONUTF8=1 python -m signet_trainer.harness_state emit. Never hand-edit "
        "inside these markers (D-30 drift fence)._"
    )
    lines.append("")
    for tier_num in sorted(tiers):
        lines.append(f"- **Tier {tier_num}** — {tiers[tier_num]}")
    lines.append("")
    lines.append("| knob | tier | fenced | source tags | behavior |")
    lines.append("| --- | --- | --- | --- | --- |")
    for name, meta in rows:
        tier = meta.get("tier", 3)
        fenced = "HARD-FENCED (D-07)" if meta.get("fenced") else "—"
        tags = meta.get("source_tags", "")
        note = str(meta.get("note", "")).replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{name}` | {tier} | {fenced} | {tags} | {note} |")
    lines.append("")
    lines.append("**Not a mode lever (off-axis — NO tier is inferable for these):**")
    for entry in taxonomy.get("not_a_mode_lever", []) or []:
        if isinstance(entry, dict):
            for key, val in entry.items():
                val = str(val).replace("\n", " ")
                lines.append(f"- `{key}` — {val}")
    return "\n".join(lines)


# --------------------------------------------------------------------------- mask spec block

# harness_state's OWN required-key set for the mask spec. It deliberately duplicates the shape-check
# in ``prep/spec.py::load_mask_spec`` — the emitter must NOT import the ``prep`` package (the
# import-confinement test allows only ``session_cap`` as a signet-internal import), so it carries its
# own fail-loud loader. The two loaders staying in sync is a cheap price for import independence.
_MASK_SPEC_REQUIRED = ("hex", "chroma", "thresholds", "polarity", "coverage_bands", "dims")


def load_mask_spec(path: str | Path) -> dict:
    """Load + shape-check the typed mask spec (``MASK-SPEC.yaml``). Fails LOUD.

    Mirrors ``load_tier_taxonomy`` / ``load_house_spec``: ``FileNotFoundError`` on absence (the mask
    spec is house law, never "no constraint") and ``ValueError`` naming the file when the top level
    is not a mapping or any of ``{hex, chroma, thresholds, polarity, coverage_bands, dims}`` is
    missing. This is the EMITTER's loader (independent of ``prep/spec.py`` — see ``_MASK_SPEC_REQUIRED``).
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"mask spec file not found: {path} (the mask spec is house law)")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"mask spec {path}: top level must be a mapping, got {type(data).__name__}")
    missing = [k for k in _MASK_SPEC_REQUIRED if k not in data]
    if missing:
        raise ValueError(
            f"mask spec {path}: missing required keys {missing}; a half-written mask spec must "
            f"never render a plausible convention block"
        )
    if not isinstance(data["coverage_bands"], dict) or not data["coverage_bands"]:
        raise ValueError(
            f"mask spec {path}: 'coverage_bands' must be a non-empty mapping of subject-class bands"
        )
    return data


def render_mask_spec_block(spec: dict) -> str:
    """Render the mask conventions as a deterministic markdown block (D-03 drift fence).

    Mirrors ``render_tier_table``: a markdown block with NO ``#``-prefixed lines (KNOWLEDGE.md's
    section scanner would mis-parse them as headings), source-tagged claims (satisfies
    ``test_knowledge_recommendation_sections_are_source_tagged``), byte-identical on re-render. The
    per-class coverage target + auto-extend dilation margin rows document the D-02 behavior.
    """
    chroma = spec.get("chroma", {}) or {}
    thresholds = spec.get("thresholds", {}) or {}
    dims = spec.get("dims", {}) or {}
    polarity = spec.get("polarity", {}) or {}
    chain = polarity.get("chain", []) or []

    lines: list[str] = []
    lines.append(
        "_Generated from src/signet_trainer/harness_data/MASK-SPEC.yaml — edit that file, then regenerate: "
        "PYTHONPATH=src PYTHONUTF8=1 python -m signet_trainer.harness_state emit. Never hand-edit "
        "inside these markers (D-03 drift fence)._"
    )
    lines.append("")
    lines.append(
        f"- **Brush hex** `{spec.get('hex')}` (RGB {spec.get('rgb')}) — the D-01 canonical teal. "
        "`[house]` `[precedent]`"
    )
    lines.append(
        f"- **Chroma extraction** — method `{chroma.get('method')}` "
        f"(alternate `{chroma.get('alternate_method')}`), tolerance `{chroma.get('tolerance')}`. "
        "`[house]`"
    )
    lines.append(
        f"- **Binarize thresholds** — seed load `>{thresholds.get('seed_load')}`, "
        f"encode `>{thresholds.get('encode_binarize')}`. `[house]`"
    )
    lines.append(
        "- **Polarity chain (D-05)** — "
        + " → ".join(str(step) for step in chain)
        + ". Inverting any link is silent until render. `[house]`"
    )
    lines.append(
        f"- **Inpaint dims** — ÷{dims.get('spatial_divisor')} spatial + "
        f"`{dims.get('frame_rule')}` frames (trim, never pad). `[house]`"
    )
    lines.append("")
    lines.append("| subject class | coverage target | warn below | dilation max margin (px) | grow to target |")
    lines.append("| --- | --- | --- | --- | --- |")
    for name in sorted(spec.get("coverage_bands", {}) or {}):
        band = spec["coverage_bands"][name] or {}
        dil = band.get("dilation", {}) or {}
        lines.append(
            f"| `{name}` | {band.get('target')} | {band.get('warn_below')} | "
            f"{dil.get('max_margin_px')} | {dil.get('grow_to_target')} |"
        )
    lines.append("")
    lines.append(
        "Coverage targets + per-class dilation margins are the D-02 auto-extend knob (exact-SAM "
        "~4.8% HURT likeness; extended ~14% won) — tunable per campaign, never hardcoded in code. "
        "`[house]` `[precedent]`"
    )
    return "\n".join(lines)


# --------------------------------------------------------------------------- rendering


def render_state_block(sources: dict) -> str:
    """Render the yaml-code-fenced TYPED-STATE block from loaded sources.

    ``sources`` = ``{"campaign": <load_campaign_state dict>, "ledger": <read_ledger_figures
    dict>}``. Deterministic (no timestamps): re-emitting with unchanged sources is a byte-level
    no-op, so idempotency is checkable and git diffs carry only real state changes. The block's
    inner YAML round-trips through ``yaml.safe_load`` — every value stays a quotable
    ``name: value`` slot, never prose.

    One canonical block is emitted into every registered artifact (STATE.md's "compact form is
    fine" is satisfied by the same block; per-artifact form variants are a future registry seam).
    """
    campaign_data = sources["campaign"]
    ledger = sources["ledger"]
    campaign = campaign_data["campaign"]
    rounds = campaign_data["rounds"]

    # verdict==null marks an in-flight round (schema note in the .state.yaml).
    completed = [r for r in rounds if isinstance(r, dict) and r.get("verdict")]
    in_flight = [r for r in rounds if isinstance(r, dict) and not r.get("verdict")]

    payload: dict = {
        "campaign": campaign["slug"],
        "campaign_phase": campaign["phase"],
        # D-13/D-14: the campaign-durable optimization posture, rendered into every emitted block so
        # it survives compaction. ``.get(..., "draft")`` is the D-15 fail-safe (mirroring the
        # missing-value idiom in ``read_ledger_figures``): an un-migrated card that predates the axis
        # renders ``draft`` rather than raising — the emitter never hard-requires the slot.
        "optimization_target": campaign.get("optimization_target", "draft"),
        "current": campaign_data["current"],
        "rounds_recorded": len(rounds),
    }
    if completed:
        last = completed[-1]
        payload["latest_round"] = {
            key: last.get(key)
            for key in ("round", "final_checkpoint", "steps", "final_loss", "verdict")
        }
    if in_flight:
        payload["in_flight"] = [
            {key: r.get(key) for key in ("round", "config", "init_adapter", "steps")}
            for r in in_flight
        ]
    payload["ledger"] = {
        "session_cap_usd": ledger["session_cap_usd"],
        "spent_est_usd": ledger["spent_est_usd"],
        "entries": ledger["entries"],
        "source": ledger["source"],
    }

    inner = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=4096)
    # The campaign-source path in the header is threaded by the caller (emit_all sets it to the
    # DISCOVERED card path); direct render calls without it get the generic cards-dir pointer.
    campaign_src = sources.get(
        "campaign_source", f"{CARDS_DIR}/{CARD_STATE_PREFIX}<slug>{CARD_STATE_SUFFIX}"
    )
    header = (
        f"# EMITTED from {campaign_src} + {ledger['source']} — edit the sources, then\n"
        "# regenerate: PYTHONPATH=src PYTHONUTF8=1 python -m signet_trainer.harness_state emit\n"
    )
    return "```yaml\n" + header + inner + "```"


# --------------------------------------------------------------------------- emission


def _splice(
    text: str,
    block: str,
    anchor: str | None,
    where: str,
    *,
    marker_begin: str = MARKER_BEGIN,
    marker_end: str = MARKER_END,
    begin_prefix: str = _MARKER_BEGIN_PREFIX,
    end_prefix: str = _MARKER_END_PREFIX,
) -> tuple[str, str]:
    """Pure splice: return ``(new_text, action)`` with action in {replaced, created, unchanged}.

    Fails LOUD (ValueError) on malformed markers: duplicated/nested pairs, unbalanced BEGIN/END,
    END before BEGIN, or missing markers with no findable anchor. Never guesses an ownership
    boundary — a malformed artifact is fixed by hand, not silently rewritten.

    The marker set is parametrized (default: the TYPED-STATE markers) so a single file can carry
    MULTIPLE distinct emitted blocks — each identified by its own ``BEGIN``/``END`` prefix — without
    ``_splice`` counting one block type's markers against another (KNOWLEDGE.md holds both the tier
    table and the mask-spec block).
    """
    lines = text.split("\n")
    begins = [i for i, line in enumerate(lines) if line.lstrip().startswith(begin_prefix)]
    ends = [i for i, line in enumerate(lines) if line.lstrip().startswith(end_prefix)]

    if len(begins) > 1 or len(ends) > 1:
        raise ValueError(
            f"{where}: found {len(begins)} TYPED-STATE:BEGIN / {len(ends)} TYPED-STATE:END markers — "
            "duplicated or nested marker sections are malformed; fix the artifact by hand"
        )
    if len(begins) != len(ends):
        raise ValueError(
            f"{where}: unbalanced TYPED-STATE markers ({len(begins)} BEGIN vs {len(ends)} END) — "
            "malformed; fix the artifact by hand"
        )

    block_lines = block.split("\n")

    if begins:  # replace the owned section, canonicalizing the marker lines themselves
        begin_idx, end_idx = begins[0], ends[0]
        if end_idx < begin_idx:
            raise ValueError(
                f"{where}: TYPED-STATE:END (line {end_idx + 1}) precedes TYPED-STATE:BEGIN "
                f"(line {begin_idx + 1}) — malformed; fix the artifact by hand"
            )
        new_lines = lines[:begin_idx] + [marker_begin, *block_lines, marker_end] + lines[end_idx + 1:]
        new_text = "\n".join(new_lines)
        return new_text, ("unchanged" if new_text == text else "replaced")

    # No markers yet: create the section immediately after the anchor heading.
    if not anchor:
        raise ValueError(
            f"{where}: no TYPED-STATE markers found and no anchor heading given — cannot create the section"
        )
    anchor_hits = [i for i, line in enumerate(lines) if line.startswith(anchor)]
    if not anchor_hits:
        raise ValueError(
            f"{where}: anchor heading {anchor!r} not found — cannot create the TYPED-STATE section"
        )
    insert_at = anchor_hits[0] + 1
    section = ["", marker_begin, *block_lines, marker_end]
    tail = lines[insert_at:]
    if tail and tail[0].strip():
        section.append("")  # keep a blank line between the section and following prose
    return "\n".join(lines[:insert_at] + section + tail), "created"


def emit_into(
    artifact_path: str | Path,
    block: str,
    anchor: str | None = None,
    dry_run: bool = False,
    *,
    marker_begin: str = MARKER_BEGIN,
    marker_end: str = MARKER_END,
    begin_prefix: str = _MARKER_BEGIN_PREFIX,
    end_prefix: str = _MARKER_END_PREFIX,
) -> str:
    """Replace (or create-after-``anchor``) the marker section of ``artifact_path``.

    Returns the action taken: ``"replaced"`` / ``"created"`` / ``"unchanged"``. Idempotent — the
    same ``block`` twice yields a byte-identical file. Preserves the artifact's existing newline
    style (LF/CRLF) and touches NOTHING outside the marker pair. ``dry_run=True`` computes the
    action (including all malformed-marker validation) without writing.

    The marker set defaults to the TYPED-STATE markers; pass ``MASK_SPEC_MARKER_*`` /
    ``_MASK_SPEC_*_PREFIX`` to emit the mask-spec block into a file that ALSO carries a TYPED-STATE
    block (KNOWLEDGE.md) — the distinct prefixes keep the two blocks independent.
    """
    path = Path(artifact_path)
    raw = path.read_bytes().decode("utf-8")
    crlf = "\r\n" in raw
    text = raw.replace("\r\n", "\n") if crlf else raw

    new_text, action = _splice(
        text,
        block,
        anchor,
        where=str(path),
        marker_begin=marker_begin,
        marker_end=marker_end,
        begin_prefix=begin_prefix,
        end_prefix=end_prefix,
    )
    if action != "unchanged" and not dry_run:
        out = new_text.replace("\n", "\r\n") if crlf else new_text
        path.write_bytes(out.encode("utf-8"))
    return action


def emit_all(
    dry_run: bool = False,
    repo_root: Path | None = None,
    *,
    taxonomy_source: Path | None = None,
    mask_spec_source: Path | None = None,
) -> list[tuple[str, str]]:
    """Render one canonical block and emit it into every registered artifact.

    Returns ``[(artifact_relpath, action), ...]``. Pure-local: reads the typed sources — LIVE state
    from ``repo_root`` (the campaign card + the ledger) and the PACKAGED specs from
    ``signet_trainer.harness_data`` — and writes the registered prose artifacts (or nothing under
    ``dry_run``).

    ``taxonomy_source`` / ``mask_spec_source`` override the packaged specs with explicit files.
    They exist because the specs moved OUT of the repo tree into package data: a fixture repo can
    no longer inject a controlled taxonomy/mask-spec just by writing one under its own root, so the
    injection has to be an argument. Production passes neither.
    """
    root = project_root(repo_root)
    campaign_rel = discover_campaign_state_path(root)
    sources = {
        "campaign": load_campaign_state(root / campaign_rel),
        "ledger": read_ledger_figures(root / SESSION_STATE_PATH),
        # Keep both source paths repo-relative in the rendered block (stable across machines).
        "campaign_source": campaign_rel,
    }
    sources["ledger"]["source"] = SESSION_STATE_PATH
    block = render_state_block(sources)

    results: list[tuple[str, str]] = []
    for rel_path, anchor in artifact_registry(root):
        action = emit_into(root / rel_path, block, anchor=anchor, dry_run=dry_run)
        results.append((rel_path, action))

    # Second emission (D-30 part 2): the knob->tier table, GENERATED from TIER-TAXONOMY.yaml, into
    # KNOWLEDGE.md. ``emit_into`` is block-agnostic so no _splice change is needed. Because
    # ``check_stale`` delegates to ``emit_all(dry_run=True)``, KNOWLEDGE.md drift is covered by the
    # existing backstop with zero extra code.
    taxonomy = load_tier_taxonomy(taxonomy_source or tier_taxonomy_path())
    tier_block = render_tier_table(taxonomy)
    tax_rel, tax_anchor = TAXONOMY_ARTIFACT
    tax_action = emit_into(root / tax_rel, tier_block, anchor=tax_anchor, dry_run=dry_run)
    results.append((tax_rel, tax_action))

    # Third emission (Plan 09.3-01): the mask conventions block, GENERATED from MASK-SPEC.yaml, into
    # KNOWLEDGE.md under its OWN anchor + its OWN marker type (distinct from the tier table's
    # TYPED-STATE markers so both blocks coexist in one file). ``check_stale`` covers mask-spec drift
    # for FREE via its ``emit_all(dry_run=True)`` delegation — no separate stale path.
    mask_spec = load_mask_spec(mask_spec_source or mask_spec_path())
    mask_block = render_mask_spec_block(mask_spec)
    ms_rel, ms_anchor = MASK_SPEC_ARTIFACT
    ms_action = emit_into(
        root / ms_rel,
        mask_block,
        anchor=ms_anchor,
        dry_run=dry_run,
        marker_begin=MASK_SPEC_MARKER_BEGIN,
        marker_end=MASK_SPEC_MARKER_END,
        begin_prefix=_MASK_SPEC_BEGIN_PREFIX,
        end_prefix=_MASK_SPEC_END_PREFIX,
    )
    results.append((ms_rel, ms_action))
    return results


# --------------------------------------------------------------------------- staleness check


def check_stale(
    repo_root: Path | None = None,
    *,
    taxonomy_source: Path | None = None,
    mask_spec_source: Path | None = None,
) -> list[tuple[str, str]]:
    """Return the registered artifacts whose emitted block has DRIFTED from the typed sources.

    Runs ``emit_all(dry_run=True, ...)`` — a byte-identical block renders ``"unchanged"``; any
    ``"replaced"`` / ``"created"`` means the prose TYPED-STATE block no longer matches what the
    typed sources (``<card>.state.yaml`` + ``SESSION-STATE.json``) would render. That is the
    D-TS-4 staleness backstop: it catches the exact hand-copy failure class the emitter was built
    to kill (a hand-edit inside the markers, or a source mutated without a re-emit). Returns
    ``[(artifact_relpath, action), ...]`` for every drifted artifact — empty means all fresh.
    """
    return [
        (rel, action)
        for rel, action in emit_all(
            dry_run=True,
            repo_root=repo_root,
            taxonomy_source=taxonomy_source,
            mask_spec_source=mask_spec_source,
        )
        if action != "unchanged"
    ]


# --------------------------------------------------------------------------- CLI


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m signet_trainer.harness_state",
        description="Emit the generated TYPED-STATE blocks into the registered prose artifacts.",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    emit_parser = sub.add_parser("emit", help="render + write the TYPED-STATE marker sections")
    emit_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the rendered block and per-artifact actions; write nothing",
    )
    check_parser = sub.add_parser(
        "check",
        help="staleness backstop: FAIL if any emitted TYPED-STATE block drifted from its sources",
    )
    check_parser.add_argument(
        "--repo-root",
        default=None,
        help="project root to check (default: resolved by project_root() — SIGNET_PROJECT_ROOT, "
        "else the nearest ancestor of the CWD carrying .planning/harness); set for CI / fixtures",
    )
    verdict_parser = sub.add_parser(
        "assert-verdict-spec",
        help="dispatch-time gate: assert a render config's validation block matches the house verdict spec",
    )
    verdict_parser.add_argument(
        "--config", required=True, help="render config YAML whose 'validation:' block is asserted"
    )
    verdict_parser.add_argument(
        "--render-tier",
        default="verdict",
        help="quicklook | verdict (default: verdict — the strict/fail-safe direction; an undeclared "
        "tier is treated as a verdict and gets the strict check, never waved through)",
    )
    args = parser.parse_args(argv)

    if args.command == "emit":
        root = project_root()
        if args.dry_run:
            campaign_rel = discover_campaign_state_path(root)
            sources = {
                "campaign": load_campaign_state(root / campaign_rel),
                "ledger": read_ledger_figures(root / SESSION_STATE_PATH),
                "campaign_source": campaign_rel,
            }
            sources["ledger"]["source"] = SESSION_STATE_PATH
            print("[harness_state] rendered block:\n")
            print(render_state_block(sources))
            print()
        results = emit_all(dry_run=args.dry_run, repo_root=root)
        mode = "DRY-RUN, nothing written" if args.dry_run else "written"
        for rel_path, action in results:
            print(f"[harness_state] {action:9s} ({mode}): {rel_path}")
        return 0

    if args.command == "check":
        root = Path(args.repo_root) if args.repo_root else None
        drifted = check_stale(repo_root=root)
        if drifted:
            print(f"[harness_state] STALE — {len(drifted)} artifact(s) drifted from the typed sources:")
            for rel_path, action in drifted:
                print(f"  - {action:9s}: {rel_path}  (re-run 'harness_state emit' to regenerate)")
            return 1
        print("[harness_state] fresh: every TYPED-STATE block matches its typed sources")
        return 0

    if args.command == "assert-verdict-spec":
        house_spec = load_house_spec(house_spec_path())
        root = project_root()
        config_path = Path(args.config)
        if not config_path.is_file() and (root / args.config).is_file():
            config_path = root / args.config
        cfg = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        validation = cfg.get("validation", {}) if isinstance(cfg, dict) else {}
        if not isinstance(validation, dict):
            validation = {}
        try:
            assert_verdict_spec(validation, args.render_tier, house_spec)
        except ValueError as exc:
            print(f"[harness_state] verdict-spec FAIL ({args.render_tier}): {args.config}\n{exc}")
            return 1
        print(f"[harness_state] verdict-spec OK ({args.render_tier}): {args.config}")
        return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
